//generate claims to api (only all get methods)

GET http://localhost:8080/products
Accept: application/json

###
GET http://localhost:8080/products/1
Accept: application/json

###
GET http://localhost:8080/products/9
Accept: application/json

###
GET http://localhost:8080/products/category/smartphones
Accept: application/json

###
GET http://localhost:8080/products/category/computers
Accept: application/json

//now by search
###
GET http://localhost:8080/products/search/asus
Accept: application/json