### Crear producto - Laptop
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Laptop Gamer Asus ROG Strix",
  "price": 5299.99,
  "stock": 10,
  "category": "COMPUTERS",
  "description": "Laptop para gaming con procesador Intel i7, 16GB RAM y tarjeta gráfica NVIDIA RTX 3060",
  "imageUrl": "https://example.com/images/laptop-asus.jpg"
}

### 
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Smartphone Samsung Galaxy S21",
  "price": 799.99,
  "stock": 25,
  "category": "SMARTPHONES",
  "description": "Smartphone con pantalla AMOLED, cámara de 64MP y batería de larga duración",
  "imageUrl": "https://example.com/images/samsung-galaxy-s21.jpg"
}



###
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "price": 4799.99,
  "stock": 15,
  "description": "Actualización: Laptop para gaming con procesador Intel i7, 16GB RAM y tarjeta gráfica NVIDIA RTX 3070",
  "imageUrl": "https://example.com/images/laptop-asus-updated.jpg"
}

###
DELETE http://localhost:8080/products/2
