### Obtener todos los usuarios
GET http://localhost:8080/auth
Authorization: Basic aG9sYTpob2xh


### Obtener usuarios por rol (ADMIN)
GET http://localhost:8080/auth/ADMIN
Authorization: Basic cGVwZTo2NTQzMjE=


### Obtener usuarios por rol (USER)
GET http://localhost:8080/auth/USER
Authorization: Basic Y3VzdG9tZXI6NjU0MzIx


### Buscar usuario por username
GET http://localhost:8080/auth/search?username=admin
Authorization: Basic YWRtaW46YWRtaW4xMjM=


### Crear usuario ADMIN
POST http://localhost:8080/auth
Content-Type: application/json
Authorization: Basic aG9sYTpob2xh

{
  "username": "customer",
  "password": "654321",
  "disabled": false,
  "role": "USER"
}


### Eliminar usuario
DELETE http://localhost:8080/auth/manuel
Authorization: Basic admin:admin123
